export enum CurrencyType {
    'USD-BRL' = 'Dólar Comercial',
    'USDT-BRL' = 'Dólar Turismo',
    'CAD-BRL' = 'Dólar Canadense',
    'AUD-BRL' = 'Dólar Australiano',
    'EUR-BRL' = 'Euro',
    'GBP-BRL' = 'Libra Esterlina',
    'ARS-BRL' = 'Peso Argentino',
    'JPY-BRL' = 'Iene Japonês',
    'CHF-BRL' = 'Franco Suíço',
    'CNY-BRL' = 'Yuan Chinês',
    'YLS-BRL' = 'Novo Shekel Israelense',
    'BTC-BRL' = 'Bitcoin',
    'LTC-BRL' = 'Litecoin',
    'ETH-BRL' = 'Ethereum',
    'XRP-BRL' = 'Ripple',
}
